findUnreferenced file request + add deleteFilesForDeletedType…
Coreoz/Plume-file pull request #11
Opened 2023-05-15 14:02 UTC by lucas-amiaud

2023-05-16 10:26 UTC, amanteaux requested changes

2023-05-16 10:26 UTC, amanteaux commented on plume-file-metadata-database/src/main/java/com/coreoz/plume/file/db/FileMetadataDatabaseDao.java
> +    public List<String> findFilesForDeletedTypes(List<String> deletedFileTypes) {
Je l'aurais plutôt fait comme Wail : en précisant les files types qui restent. Car généralement, on a plus les types qui ont été supprimés.

On aurait alors la fonction :
`findFilesHavingUnsedTypes(List<String> remainingFileTypes)`

2023-05-16 10:26 UTC, amanteaux commented on plume-file-core/src/main/java/com/coreoz/plume/file/services/FileService.java
> +    public void deleteFilesForDeletedTypes(List<String> deletedFileTypes) throws UncheckedIOException {
Si la méthode n'est pas appelé dans le job de nettoyage, il faudrait référencer cette méthode dans le readme

2023-05-16 12:09 UTC, lucas-amiaud commented on plume-file-metadata-database/src/main/java/com/coreoz/plume/file/db/FileMetadataDatabaseDao.java
> +    public List<String> findFilesForDeletedTypes(List<String> deletedFileTypes) {
mmh du coup autant utiliser directement les files types du projet ?

2023-05-16 17:17 UTC, amanteaux requested changes

2023-05-16 17:17 UTC, amanteaux commented on plume-file-core/src/main/java/com/coreoz/plume/file/services/FileService.java
> +    public void deleteFilesForDeletedTypes() throws UncheckedIOException {
Même chose ici avec le having : `deleteFilesHavingDeletedTypes`

2023-05-17 10:06 UTC, amanteaux requested changes

2023-05-17 10:06 UTC, amanteaux commented on plume-file-core/src/main/java/com/coreoz/plume/file/services/FileService.java
> +     * This method must be use with caution and punctually, as it can lead to errors
Delete files having a type that longer exists in the {@link FileType} enum and can't be linked to stored files.
This method should be used punctually only when a file type is deleted. Else unwanted files could be deleted in a shared metadata database environment.

2023-05-17 10:06 UTC, amanteaux commented on plume-file-core/src/main/java/com/coreoz/plume/file/services/FileService.java
> +     * @throws UncheckedIOException is a file could not be deleted. This may happen if the file is still referenced.
UncheckedIOException is a file could not be deleted. This may happen if file storage service cannot delete the file.

2023-05-17 10:12 UTC, merged